version: "3.9"

services:
  api:
    build: .
    container_name: trading-fastapi
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
        echo '✅ Database is ready, running Alembic migrations' &&
        alembic upgrade head &&
        echo '🚀 Starting FastAPI...' &&
        uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
      "

  db:
    image: postgres:15
    container_name: trading-postgres
    restart: always
    environment:
      POSTGRES_USER: ramy
      POSTGRES_PASSWORD: Azert-11
      POSTGRES_DB: trading_simulator
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ramy -d trading_simulator"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  
  redis:
    image: redis:7
    container_name: trading-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  pgdata:
