"""position_id_added_to_bots

Revision ID: 1bb53505e6fb
Revises: 27e1abbb6a80
Create Date: 2025-12-03 12:21:49.308687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb53505e6fb'
down_revision: Union[str, None] = '27e1abbb6a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bots', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.drop_column('bots', 'position_id')
    # ### end Alembic commands ###
