"""Add chat tables

Revision ID: 2cf5e5070eb1
Revises: a857b10ac2e3
Create Date: 2025-12-03 21:24:52.753212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf5e5070eb1'
down_revision: Union[str, None] = 'a857b10ac2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'bot_initial_capital',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('bots', 'bot_current_value',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('portfolios', 'margin_level',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'margin_level',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('bots', 'bot_current_value',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('bots', 'bot_initial_capital',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
