"""position_id_added_to_bots2

Revision ID: a857b10ac2e3
Revises: 1bb53505e6fb
Create Date: 2025-12-03 12:30:25.720074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a857b10ac2e3'
down_revision: Union[str, None] = '1bb53505e6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
